name: Build vscode:bun image

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
    paths:
      - 'images/vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: faasjs/vscode:${{ github.sha }},faasjs/vscode:bun
          file: ./images/vscode/bun.Dockerfile
          context: ./images/vscode
          cache-from: type=gha
          cache-to: type=gha,mode=max
