name: Build node image

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
    paths:
      - 'images/node/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: faasjs/node:${{ github.sha }},faasjs/node:latest
          context: ./images/node
          cache-from: type=gha
          cache-to: type=gha,mode=max
