name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
  pull_request:
    paths:
      - 'packages/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - name: Install
        run: |
          npm install -g npm@latest
          npm ci
      - name: Run Lint
        run: npm run lint .
